### ISSUE TITLE
联系管理员插件相关问题

### ISSUE THREAD

**Issue by Windsland52** [zhenxun-org/zhenxun_bot_plugins#15]
```
09-21 15:28:16 [ERROR] nonebot | Running Matcher(type='message', module=zhenxun.plugins.dialogue, lineno=48) failed.
Traceback (most recent call last):

  File "/home/ubuntu/zhenxun_bot/bot.py", line 28, in <module>
    nonebot.run()
    │       └ <function run at 0x7abef1615d00>
    └ <module 'nonebot' from '/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.12/lib/python3.12/site-packages/non...

  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.12/lib/python3.12/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7abef1ec1080>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.12/lib/python3.12/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
    │       └ <function run at 0x7abef0bab1a0>
    └ <module 'uvicorn' from '/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.12/lib/python3.12/site-packages/uvi...
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.12/lib/python3.12/site-packages/uvicorn/main.py", line 577, in run
    server.run()
    │      └ <function Server.run at 0x7abef0bab380>
    └ <uvicorn.server.Server object at 0x7abed5006480>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.12/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7abef0bab420>
           │       │   └ <uvicorn.server.Server object at 0x7abed5006480>
           │       └ <function run at 0x7abef315c680>
           └ <module 'asyncio' from '/usr/lib/python3.12/asyncio/__init__.py'>
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x7abed4e19620>
           │      └ <function Runner.run at 0x7abef25f67a0>
           └ <asyncio.runners.Runner object at 0x7abed4f9a1b0>
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Server.serve() running at /home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3...
           │    │     └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           │    └ <uvloop.Loop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7abed4f9a1b0>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.12/lib/python3.12/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
          └ <function _run_matcher at 0x7abef14fcf40>
> File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.12/lib/python3.12/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _uni_msg at 0x7abeeec4e700>: <Task finished name='Task-212984' coro=<_uni_msg() done, defined at /home/ubuntu/.cac...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7abed370ad20>
          │       │   │    │      └ {'_prefix': {'command': ('滴滴滴-',), 'raw_command': '滴滴滴-', 'command_arg': [MessageSegment(type='text', data={'text': '我喜欢你'})]...
          │       │   │    └ GroupMessageEvent(time=1726903696, self_id=botqq号, post_type='message', sub_type='normal', user_id=发送人qq, message_typ...
          │       │   └ Bot(type='OneBot V11', self_id='botqq号')
          │       └ <function Matcher.run at 0x7abef164ba60>
          └ Matcher(type='message', module=zhenxun.plugins.dialogue, lineno=48)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.12/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _uni_msg at 0x7abeeec4e700>: <Task finished name='Task-212984' coro=<_uni_msg() done, defined at /home/ubuntu/.cac...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7abed370ad20>
          │    │          │    │      └ {'_prefix': {'command': ('滴滴滴-',), 'raw_command': '滴滴滴-', 'command_arg': [MessageSegment(type='text', data={'text': '我喜欢你'})]...
          │    │          │    └ GroupMessageEvent(time=1726903696, self_id=botqq号, post_type='message', sub_type='normal', user_id=发送人qq, message_typ...
          │    │          └ Bot(type='OneBot V11', self_id='botqq号')
          │    └ <function Matcher.simple_run at 0x7abef164b9c0>
          └ Matcher(type='message', module=zhenxun.plugins.dialogue, lineno=48)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.12/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
          └ Dependent(call=_)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.12/lib/python3.12/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='botqq号'), 'message': [Text(text='*****一份交流报告*****\n', styles={}), Text(text='Id: ...
                 │    │             │         │    │    └ <function _ at 0x7abedbbcd6c0>
                 │    │             │         │    └ Dependent(call=_)
                 │    │             │         └ ~R
                 │    │             └ <class 'collections.abc.Awaitable'>
                 │    └ typing.Callable
                 └ <function cast at 0x7abef2a93920>

  File "/home/ubuntu/zhenxun_bot/zhenxun/plugins/dialogue/__init__.py", line 86, in _
    await message.send(bot=bot, target=Target(superuser_id, private=True))
          │       │        │           │      └ ['管理员qq']
          │       │        │           └ <class 'nonebot_plugin_alconna.uniseg.target.Target'>
          │       │        └ Bot(type='OneBot V11', self_id='botqq号')
          │       └ <function UniMessage.send at 0x7abeeec4d800>
          └ [Text(text='*****一份交流报告*****\n', styles={}), Text(text='Id: 2\n', styles={}), Text(text='昵称: 发送人昵称(发送人qq)\n', styles={}), ...

  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.12/lib/python3.12/site-packages/nonebot_plugin_alconna/uniseg/message.py", line 1395, in send
    res = await fn.send_to(target, bot, msg, **kwargs)
                │  │       │       │    │      └ {}
                │  │       │       │    └ [MessageSegment(type='text', data={'text': '*****一份交流报告*****\nId: 2\n昵称: 发送人昵称(发送人qq号)\n群组: 信息来源群组(群号)\n消息:\n 我喜欢你...
                │  │       │       └ Bot(type='OneBot V11', self_id='botqq号')
                │  │       └ Target({'id': ['管理员qq'], 'parent_id': '', 'channel': False, 'private': True, 'self_id': None, 'extra': {}, 'scope': None...
                │  └ <function Onebot11MessageExporter.send_to at 0x7abeeec06c00>
                └ <nonebot_plugin_alconna.uniseg.adapters.onebot11.exporter.Onebot11MessageExporter object at 0x7abeeeba6300>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/zhenxun-bot-rULbFS0_-py3.12/lib/python3.12/site-packages/nonebot_plugin_alconna/uniseg/adapters/onebot11/exporter.py", line 157, in send_to
    return await bot.send_msg(message_type="private", user_id=int(_target.id), message=message, **kwargs)
                 │                                                │       │            │          └ {}
                 │                                                │       │            └ [MessageSegment(type='text', data={'text': '*****一份交流报告*****\nId: 2\n昵称: 发送人昵称(发送人qq号)\n群组: 发送信息来源(群号)\n消息:\n 我喜欢你...
                 │                                                │       └ ['管理员账号']
                 │                                                └ Target({'id': ['管理员账号'], 'parent_id': '', 'channel': False, 'private': True, 'self_id': None, 'extra': {}, 'scope': None...
                 └ Bot(type='OneBot V11', self_id='botqq号')

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'
```
测试功能时报错，log已将敏感信息处理，仅替换相关字符串、qq号等信息，未删改`“”[]()`等符号。
使用的napcatqq和zhenxun_bot均为最新。

**Comment by HibiKier** [comment]
#19
